### PR TITLE
.gitmodules: use https://github.com/...

### PR DESCRIPTION
**Pull request by RandyMcMillan**
Using https://  in submodule urls is preferred for this project.

### CODE REVIEW

**Comment by pedro-vicente** [comment]
I fixed the github authentication error on my last commit

added this to the build script

git clone --recursive --depth=1 https://github.com/boostorg/boost.git ext/boost_1_82_0
git checkout boost-1.82.0

and then added to
 .gitmodules 

the list of boost modules taken from their site 
it seems the key to avoid the error is to have the modules in relative path

**Comment by pedro-vicente** [comment]
The purpose of having the boost-1.82.0 code in the repo was to avoid these issues of cloning, etc

but boost is huge, so in this case this is an exception for dependencies

.gitmodules lists all dependencies, it seems not all are needed, next is to find out which ones are needed (to build the WT web framework)

**Comment by pedro-vicente** [comment]
actually, it seems .gitmodules is not needed, so I will remove it soon

**Comment by RandyMcMillan** [comment]
I think taking this further - to include any dependancy code in the /ext folder would be better... (flat repo) - building dependancies from brew is annoying these days... mostly due to the fact that brew always forces a rebuild when a version number is bumped in a package...

Keeping the repo "flat" will also support reproducable builds in the future...

**Pull request closed without merging**
